# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1762c779fbb88dd9cec90c8fe647ba3d1c3487fe653d5ff2823f8a8ca036723832e547577e5246227153bbae157fc5f1024e5789e00ab28fce384fa72013e9e2

test:
  secret_key_base: b1d5954ddbfd9948286e8567eeeddb7bcb8fc90add37e172a2aa6b8f891d3418ff174c54b78f34a3551f414c4bce0a0d82fed41735205f29eb273dc01c533572

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
