version: '2'
services:
  app:
    build: .
    container_name: bionexo_app
    command: bash start.sh
    environment:
      RAILS_ENV: development
      APP_DB_HOST: bionexo_db
      APP_DB_PASSWORD: 1q2w3e
      APP_DB_USER: root
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - database
    links:
      - database
    networks:
      - bionexo-net
  
  database:
    container_name: bionexo_db
    image: mdillon/postgis:9.6
    ports:
      - "5432:5432"
    volumes:
      - ../db:/docker-entrypoint
    environment:
      POSTGRES_PASSWORD: 1q2w3e
      POSTGRES_USER: root
    networks:
      - bionexo-net

networks:
  bionexo-net:
